### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vivekanand1101** [egalpin/apt-vim#18]
Hi! I am new to linux and using ubuntu 14.04. Can you please explain how to set path on point number 7 of installation instructions.
I have tried adding to bashrc and bashrc_profile, but in both the cases, it gives the same error:
"FAILED!
/home/vivek/.vimpkg/bin not found in PATH
Please ensure that /home/vivek/.vimpkg/bin is in your PATH"

**Comment by egalpin** [comment]
Depending on your particular setup, each shell has a slightly different way of setting up user preferences. In Ubuntu, default shell is likely `bash`.  You can confirm this by running `echo $SHELL` in a terminal window (you can open terminal with `ctrl + alt + t`). You should see something like `/bin/bash`.

If that's the case, run the following to edit your bash config file (.bashrc):  `gedit ~/.bashrc` (or other editor of your choice).  Scroll to the bottom of the file and add the following:  `export PATH=$PATH:/home/<YOUR_USERNAME>/.vimpkg/bin` (be sure to use your _actual_ user name here).  Close and re-open terminal.

To verify that it's worked, run `echo $PATH`.  You should see `/home/<YOUR_USERNAME>/.vimpkg/bin` in the output.

Let me know that does it for you :-)

**Comment by vivekanand1101** [comment]
Yeah, it worked. Thank you!

**Comment by egalpin** [comment]
Awesome! Let me know if you have any other troubles. I won't close this ticket until you're up and running.

**Comment by egalpin** [comment]
Any updates? Is `apt-vim` up and running for you? If so, I'll close the issue.

**Comment by vivekanand1101** [comment]
It's running fine. Thank you.

**Comment by egalpin** [comment]
Great :)
