### ISSUE TITLE
Can't list packages using fish

### ISSUE THREAD

**Issue by aliksend** [egalpin/apt-vim#32]
Hi
Using bash when I try to `apt-vim list` I can see list of installed packages. But when I trying to do the same in [fish](http://fishshell.com/) I see that:

```
~> apt-vim list
Traceback (most recent call last):
  File "/usr/local/bin/apt-vim", line 781, in <module>
    apt_vim.main()
  File "/usr/local/bin/apt-vim", line 761, in main
    self.process_cmd_args()
  File "/usr/local/bin/apt-vim", line 737, in process_cmd_args
    missing_dependencies = self.init()
  File "/usr/local/bin/apt-vim", line 577, in init
    self.verify_bin_in_path()
  File "/usr/local/bin/apt-vim", line 570, in verify_bin_in_path
    if '.vimpkg/bin' not in os.environ['PATH']:
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'PATH'
```

My $PATH is

```
 ~> echo $PATH
/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /home/aliksend/.vimpkg/bin
```

Because I have added 

```
set -g PATH $PATH $HOME/.vimpkg/bin
```

into `~/.config/fish/config.fish`
But what is wrong?

**Comment by egalpin** [comment]
Hmm,  not 100% as I haven't used `fish` before. I'll have to investigate! 

What OS are you running? If Linux, which distro?

**Comment by egalpin** [comment]
According to an answer given [here](https://github.com/pypa/pip/issues/1871), you may need to use `set - gx ...` when setting your `PATH`. The 'x' is for 'export'. Give it a try and let me know ☺

**Comment by aliksend** [comment]
Thank you for answer
I'm using Ubuntu 14.04
And when I have changed to `set -gx ...` nothing changed in `PATH`:

```
 ~> echo $PATH
/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /home/aliksend/.vimpkg/bin
```

But `apt-vim list` is working now
Thank you
