### ISSUE TITLE
Init errors out on missing vim_config.json

### ISSUE THREAD

**Issue by leetrout** [egalpin/apt-vim#33]
I was following the manual setup and cloned the repo and ran `./apt-vim init`

```
Traceback (most recent call last):
  File "./apt-vim", line 780, in <module>
    apt_vim = aptvim()
  File "./apt-vim", line 105, in __init__
    self.VIM_CONFIG = self.load_vim_config() if VIM_CONFIG is None else VIM_CONFIG
  File "./apt-vim", line 124, in load_vim_config
    json_file = open(file_path).read()
IOError: [Errno 2] No such file or directory: '/home/lee/.vimpkg/vim_config.json'
```

**Comment by egalpin** [comment]
Thanks for pointing this out, there's an issue with manual setup since I added the automatic setup. I'll get a fix in as soon as I can. 

In the mean time, you can get up and running by copying the `vim_config.json` in this repo to `~/.vimpkg/vim_config.json`
