### ISSUE TITLE
Unable to install on a Windows/MSYS2 environment

### ISSUE THREAD

**Issue by mateon1** [egalpin/apt-vim#36]
After using the install.sh script available from the code repository with removed occurences of sudo, the install script throws an OSError about needing symbolic link priviledge.
The exact message is the following:

```
$ ./install.sh
apt-vim setup starting
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "./apt-vim", line 543, in first_run
    os.symlink(self.INSTALL_TARGET, BUNDLE_PATH)
OSError: symbolic link privilege not held
```

**Comment by egalpin** [comment]
Hey, thanks for opening this. I'll admit first off that I haven't done a lot of Windows testing. 

Have you tried running msys2 with admin privileges? Try right-clicking the msys2 executable and selecting "run as administrator" if available. 

If that doesn't work, we'll find a work around ☺️

**Comment by egalpin** [comment]
Any success? If so, I'll close off this issue

**Comment by egalpin** [comment]
Been a while so I'm assuming this is resolved. If you continue to have trouble, please feel free to reopen this issue or create a new one.

**Comment by mateon1** [comment]
Just letting you know.
Since then I found Vundle, which worked fine for my purposes.
When I try to install apt-vim with the install script with sudo removed again, I get asked about an existing [partial/broken] install of apt-vim in my user directory. Python doesn't like reading from /dev/tty even though it works in Bash, and it crashes on that line regardless of what I do (msys as admin or otherwise).
I have given up on apt-vim, even though it sounds nice.
EDIT: I should be clear that the Python /dev/tty bug isn't the fault of apt-vim, though.

**Comment by egalpin** [comment]
fair enough, no worries.  Thanks for the feedback!  I'll try to reproduce in a windows VM and see if I can get these issues fixed.

I'm going to reopen this issue for visibility.
