### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by yanugto** [egalpin/apt-vim#48]
![qq 20170217091113](https://cloud.githubusercontent.com/assets/7939959/23048508/417a0188-f4f1-11e6-9f4a-8e4442cc3e19.jpg)

**Comment by egalpin** [comment]
Hi there, what version of Python do you have running on your machine? Thanks!

**Comment by egalpin** [comment]
This is a duplicate of #43, let's continue the conversation there ☺️
