### ISSUE TITLE
What does the 7th step "execute pathogen#infect() and then call pathogen#helptags() to ~/.vimrc" mean?

### ISSUE THREAD

**Issue by Akemi-Homura** [egalpin/apt-vim#52]
i can't understand how to do.i write 
```
execute pathogen#infect()
call pathogen#helptags()
```
in .vimrc but got 
```
vim .vimrc
Error detected while processing /home/quals/.vimrc:
line    1:
E117: Unknown function: pathogen#infect
E15: Invalid expression: pathogen#infect()
line    2:
E117: Unknown function: pathogen#helptags
Press ENTER or type command to continue
```

**Comment by egalpin** [comment]
Hi there, thanks for opening an issue; apologies for the delayed response. Judging by the provided error, it appears that the plugin [pathogen](https://github.com/tpope/vim-pathogen) was not successfully installed. 

I assume you're following the manual installation path?  Can you confirm whether previous steps succeeded?
