### ISSUE TITLE
How to uninstall apt-vim?

### ISSUE THREAD

**Issue by vieiralucas** [egalpin/apt-vim#57]
How to uninstall apt-vim?

**Comment by plgrazon** [comment]
If you're using a mac do the following:

1. Go to your root folder using the terminal. "cd"
2. List all files including hidden ones. "ls -a"
3. Remove apt-vim folder if exists. "rm -rf apt-vim"
5. Go inside the folder ".vimpkg". "cd .vimpkg"
6. Go inside the "bin" folder. "cd bin"
7. Delete apt-vim. "rm -rf apt-vim"

You've successfully uninstalled apt-vim

**Comment by vieiralucas** [comment]
Thanks!
