### ISSUE TITLE
It Deleted my... everything?

### ISSUE THREAD

**Issue by lumodon** [egalpin/apt-vim#59]
I don't know much about linux, but all my commands are gone and I don't know what to do or how to even open files now.

```
/home/user386/.zshrc:123: no such file or directory: :/home/user386/node_modules/.bin:/home/user386/bin:/home/user386/.local/bin:/usr/local/lib/node_modules/
/home/user386/.zshrc:124: no such file or directory: :/home/user386/node_modules/.bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:./node_modules/.bin:/home/user386/bin/wkhtmltox/bin:/home/user386/bin/fancy:/home/user386/.vimpkg/bin
➜  ~ apt-vim
➜  apt-vim apt-vim
zsh: command not found: apt-vim
➜  apt-vim cd ../
➜  ~ vim ~/.bashrc
zsh: command not found: vim
➜  ~ vim
zsh: command not found: vim
➜  ~ subl 
zsh: command not found: subl
➜  ~ cd .vim
cd: no such file or directory: .vim
➜  ~ cd ~/.vim
cd: no such file or directory: /home/user386/.vim
➜  ~ 

```

This is what happened after closing my terminal and opening another one. I don't know how to view previous output (only input via `history` command) but there were errors when the `curl -sL https://raw.githubusercontent.com/egalpin/apt-vim/master/install.sh | sh` ran - it said something about cannot find python.

How do i get my ~/.zshrc back?! It had SOOO many custom configurations!

Does Linux have a file backup system like windows 10 with recovery mode or anything?

**Comment by lumodon** [comment]
found it using super key and opening sublime from GNOME. Used sublime to open ~/.zshrc and at the bottom of my rc file was a couple of path exports - I commended them out and I'm able to use VIM again and my zshrc is actually still intact. But there is no `~/.vim` folder let alone `~/.vim/bundle` for backup like the guide says.

Hope this helps any non-linux gurus out there. Not sure how to use this package - but I'm going to stay away from running unknown shell scripts from now on. I'll look for a different way to get a file explorer for vim. Thanks.

**Comment by egalpin** [comment]
I apologize for the trouble this caused; there's nothing worse than a tool that's suppose to make things easier wreaking havoc on one's system. `export ...` should be valid in `zsh`, but something obviously went wrong. If you don't mind sharing what OS you were using, and any other details about your zshrc that might help prevent this for others in the future that would be greatly appreciated.

In terms of getting a file explorer for Vim, [NERDTree](https://github.com/scrooloose/nerdtree) is great.  It can be installed manually, or via any number of other package managers for vim (pathogen, vundle, etc.).  There is also a built in file explore accessible via `:Explore` or `:Sexplore` (split-explore). [ctrl-p](https://github.com/kien/ctrlp.vim) is another great tool (though not a file explorer) for finding files within your project directory. Hope that helps!

**Comment by lumodon** [comment]
Closing as "not planned" because I let too much time pass since noticing the request to follow up with more info.
I don't have access to this work laptop any longer.

If nobody else reported a similar bug this may have been a one-off highly environment specific issue.

Thank you for the useful info none-the-less.
