### ISSUE TITLE
remove instructions

### ISSUE THREAD

**Issue by ghost** [egalpin/apt-vim#62]
How can i completely remove it? 
Is there any instructions to remove it completely?

**Comment by EralpCelebi** [comment]
I think removing apt-vim folder and the ~/.vim/autoload/pathogen.vim would be enough but I am not really sure.

**Comment by egalpin** [comment]
@Fox2 this should be better documented for sure. There should simply be an `apt-vim uninstall` or `apt-vim nuke` command that gets rid of all traces of apt-vim. Until that's the case you can remove:

- `rm -rf ~/.vimpkg` -> where apt-vim install packages and dependencies
- `rm -rf ~/.vim/autoload/pathogen.vim` -> pathogen for doing the heavy lifting and actually loading the addons
